# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                   │
# ╰──────────────────────────────────────────────────────────────── ────────────────────────────────╯
id: JPFHIRExampleCreation
canonical: http://jpfhir.jp/fhir/JPFHIRExampleCreation
name: "eMunicipalCheckupImplementationGuide"
#title: "JPFHIRExampleCreation"
#description: "JPFHIRExampleCreation"
status: draft # draft | active | retired | unknown
version: 0.9.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html 
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Kazuhiko Ohe
  url: http://jpfhir.jp
  # email: test@example.org
dependencies:
  jp-core.draft1:
# to avoid warning message "The canonical URL for an Implementation Guide must point directly to the implementation guide resource, not to the Implementation Guide as a whole"
    uri: http://jpfhir.jp/fhir/core/ImplementationGuide/jp-core.draft1
    version: 1.1.0-beta

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
# dependencies:
#   hl7.fhir.us.core: 3.1.0
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#
#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#

#pages:
#  index.md:
#    title: 自治体検診HL7&reg; FHIR&reg;記述仕様書 第1版
#  tables.md:
#    title: 各表一覧

#   index.md:
#     title: Example Home
#   implementation.xml:
#   examples.xml:
#     title: Examples Overview
#     simpleExamples.xml:
#     complexExamples.xml:
#
#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array. For a
# partial list of allowed parameters see: 
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
# 
#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
#parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
#  path-resource:
#    - input/resources
#    - fsh-generated/resources
#  path-pages:
#    - input/pagecontent
#    #- input/intro-notes
#    - fsh-generated/includes
#    #- input/summaries
