name: Ohe-testing

on:
  push:
    branches: 
      - develop1.0
    paths:
      - 'fshegg/**'
  pull_request:
    branches: [ develop1.0 ]
    
jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v2
      with: 
        check-latest: true

    - name: Setup Sushi
      run: |
        sudo npm install -g fsh-sushi

    - name: Download filepp
      run: |
        sudo apt-get install filepp

    - name: Run filepp by file pre proccessor converting egg to egg.fsh
      run: | 
        while read -r f;do outfname=`basename $f .fshegg`;echo "converting $f to ./input/fsh/$outfname.fsh";filepp -b -M/usr/local/share/filepp/modules -m bigdef.pm $f >./input/fsh/$outfname.fsh;done < <(find ./fshegg -name *.fshegg -mindepth 1);

    - name: Run sushi
      run: | 
        sushi .
