name: Ohe-testing

on:
  push:
    branches: 
      - develop1.0
    paths:
      - 'fshegg/**'
      - 'sushi-config.yaml'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ develop1.0 ]
    
jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v2
      with: 
        check-latest: true

    - name: Setup Sushi
      run: |
        sudo npm install -g fsh-sushi

    - name: Setup jp-core package
      env:
        PACKAGE: jp-core.r4#1.1.1-snap
        PACKAGEREFER: jp-ereferral#0.9.1-snap

      run: |
        mkdir -p /home/runner/.fhir
        mkdir -p /home/runner/.fhir/packages
        mkdir -p /home/runner/.fhir/packages/$PACKAGE
        mkdir -p /home/runner/.fhir/packages/$PACKAGEREFER
        : # local cache にpackage をcopyして展開する
        cp ./packages_snapshot/$PACKAGE.tgz /home/runner/.fhir/packages/$PACKAGE/$PACKAGE.tgz
        tar xzf /home/runner/.fhir/packages/$PACKAGE/$PACKAGE.tgz -C /home/runner/.fhir/packages/$PACKAGE/
        cp ./packages_snapshot/$PACKAGEREFER.tgz /home/runner/.fhir/packages/$PACKAGEREFER/$PACKAGEREFER.tgz
        tar xzf /home/runner/.fhir/packages/$PACKAGEREFER/$PACKAGEREFER.tgz -C /home/runner/.fhir/packages/$PACKAGEREFER/

    - name: Download filepp
      run: |
        sudo apt-get install filepp

    - name: Run filepp by file pre proccessor converting egg to egg.fsh
      run: | 
        while read -r f;do outfname=`basename $f .fshegg`;echo "converting $f to ./input/fsh/$outfname.fsh";filepp -b  -I./fshegg  -M/usr/local/share/filepp/modules -m bigdef.pm -m foreach.pm -m bigfunc.pm  -M ./perlFunc  -m base64.pm $f >./input/fsh/$outfname.fsh;done < <(find ./fshegg -name *.fshegg );

    - name: Run sushi
      run: | 
        sushi . -o ./output-json

    - name: git setting 
      run: |
        git config --local user.email "kohe@m.u-tokyo.ac.jp"
        git config --local user.name "jami-fhir-jp-wg"

    - name: push files of directory output-json
      run: |
        git rm -rf --ignore-unmatch output-json/*
        git add  --ignore-removal --ignore-errors  ./output-json
        git commit -m "output-json"
        git push origin develop1.0
